### ISSUE TITLE
problem in get_training_sets

### ISSUE THREAD

**Issue by QNeuron** [yves-weissenberger/Multiphoton-Toolbox#12]
Hi again,

I am trying to train the classifier with that command : 

(base) C:\Users\dpag0680>python D:\Work\Code\gitDev\twoptb\twoptb\ROIs\train_roi
_finder.py -rad 7 -shifts 3 7 ferretclassifier1 D:\Work\Data\twopi\rawFerret\Nal
a\processed\Nala_area02

and got the following error: 

C:\Users\dpag0680\AppData\Local\Continuum\anaconda2\lib\site-packages\h5py\__ini
t__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `
float` to `np.floating` is deprecated. In future, it will be treated as `np.floa
t64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
D:\Work\Data\twopi\rawFerret\Nala\processed\Nala_area02\ROIs\area02-registered_d
ata-(20180520_02_17_51)-_area02_tones_ROIs.p D:\Work\Data\twopi\rawFerret\Nala\p
rocessed\Nala_area02\Nala_area02.h5

C:\Users\dpag0680\AppData\Local\Continuum\anaconda2\lib\site-packages\skimage\ut
il\dtype.py:122: UserWarning: Possible precision loss when converting from float
64 to uint16
  .format(dtypeobj_in, dtypeobj_out))
Traceback (most recent call last):
  File "D:\Work\Code\gitDev\twoptb\twoptb\ROIs\train_roi_finder.py", line 223, i
n <module>
    boutons,non_boutons = get_training_sets(sets,rad,shifts=eg_shift)
  File "D:\Work\Code\gitDev\twoptb\twoptb\ROIs\train_roi_finder.py", line 141, i
n get_training_sets
    if np.max(t_)==0:
UnboundLocalError: local variable 't_' referenced before assignment

**Comment by yves-weissenberger** [comment]
should be fixed in recent push?

**Comment by QNeuron** [comment]
Yep, Actually the hdf files were corrupted (presumably by some of the multiple crashes of the functions ?). I re-generated them from the raw data, and the classifier works now (both training and applying). There's still an issue, but that's for another issue thread :)
